let canvasHeigth = 720;
let canvasWidth = 1280;
let Stegosaurus = [];
let ExterminatedStegosaurus = [];
let StegoTotal = 1000;
let spacePressed = false;
let Obstacles = [];
let Generation = 1;
let HighestScore = 0;
let Score = 0;
let Vitesseinitial = 16;
let vitesseDeplacement = Vitesseinitial;
let compteur = 0;
let video;
let video2;
let video3;
let slider;
let stegoimg;
